# Generated by Django 3.1.1 on 2020-09-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryManagement',
            new_name='Product',
        ),
    ]
