# Generated by Django 3.1.1 on 2020-09-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0002_auto_20200917_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Brand Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(default='InventoryManagement Name', max_length=200),
        ),
    ]
