# Generated by Django 3.1.1 on 2020-09-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0004_categories_stock_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
    ]
