# Generated by Django 3.1.1 on 2020-09-20 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0005_auto_20200920_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoriesfk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.categorie'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplierfk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.supplier'),
        ),
        migrations.AddField(
            model_name='stock',
            name='productfk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryManagement.product'),
        ),
    ]
