# Generated by Django 3.1.1 on 2020-09-20 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryManagement', '0006_auto_20200920_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoriesfk',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplierfk',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='productfk',
            new_name='product',
        ),
    ]
