# Generated by Django 3.1.1 on 2020-09-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(default='First Name', max_length=200)),
                ('Last_Name', models.CharField(default='Last Name', max_length=200)),
                ('Phone_num', models.IntegerField(blank=True)),
                ('Email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
